# MCU & Bootloader for RP2040
MCU = RP2040
BOOTLOADER = rp2040

# Build Options
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
NKRO_ENABLE = yes

# Encoders & Vial
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
VIAL_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes
